export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_TICKET_BEGIN = "CREATE_TICKET_BEGIN";
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_ERROR = "CREATE_TICKET_ERROR";

export const GET_TICKETS_BEGIN = "GET_TICKETS_BEGIN";
export const GET_TICKETS_SUCCESS = "GET_TICKETS_SUCCESS";

export const SET_EDIT_TICKET = "SET_EDIT_TICKET";

export const DELETE_TICKET_BEGIN = "DELETE_TICKET_BEGIN";

export const EDIT_TICKET_BEGIN = "EDIT_TICKET_BEGIN";
export const EDIT_TICKET_SUCCESS = "EDIT_TICKET_SUCCESS";
export const EDIT_TICKET_ERROR = "EDIT_TICKET_ERROR";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";
